// Turns a question's static base text + one card's active filters into a
// natural-language sentence — without ever mutating `question.question`
// (that stays the stored template; see QuestionCard, which keeps baseQuestion
// and filters as separate state and derives the display text on every render).
//
// Phrasing style (which preposition attaches to branch/rep/model) is chosen
// from the question's *structured* calculation metadata — never by parsing
// the English text — so this generalizes to all ~99 catalogue questions
// without per-question hardcoding, per the brief's "understand the intent"
// requirement.

import { formatCurrency } from '../../data/format';
import { SOURCE_LABELS, STATUS_LABELS } from '../../data/transformations';
import type { DealershipDataset } from '../../data/types';
import type { QuestionFilterState } from './filters';
import type { Calculation, QuestionDefinition } from './types';

type PhraseStyle = 'revenue' | 'passiveParticiple' | 'generic';

/** Revenue/value questions ("What is the total revenue?") have no verb of
 * their own to hang a preposition on, so their branch/rep clauses supply one
 * ("generated by X", "through Y"). Delivered/lost-count questions already
 * contain a passive verb ("...have been delivered"), so their clauses just
 * continue it ("by X", "through Y"). Everything else gets the safe generic
 * default ("for X", "handled by Y") — always grammatical regardless of the
 * specific metric. */
function classifyStyle(calc: Calculation): PhraseStyle {
  if (calc.type === 'sum' && calc.field === 'deal_value') return 'revenue';
  if (calc.type === 'count' && (calc.condition?.status === 'delivered' || calc.condition?.status === 'lost')) {
    return 'passiveParticiple';
  }
  return 'generic';
}

function joinNatural(items: string[]): string {
  if (items.length <= 1) return items[0] ?? '';
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
}

/** `filters.dateFrom`/`dateTo` are "YYYY-MM-DD" strings straight from an
 * `<input type="date">` — reformatted here by splitting the string, not via
 * `new Date(...).getDate()`, so a timezone offset can never shift the day. */
function formatSentenceDate(isoDate: string): string {
  const [yyyy, mm, dd] = isoDate.split('-');
  return `${dd}/${mm}/${yyyy}`;
}

export function generateQuestionText(question: QuestionDefinition, filters: QuestionFilterState, raw: DealershipDataset): string {
  const supported = new Set(question.supportedFilters);
  const style = classifyStyle(question.calculation);
  const clauses: string[] = [];

  if (supported.has('branch') && filters.branchIds.length > 0) {
    const names = filters.branchIds.map((id) => raw.branches.find((b) => b.id === id)?.name ?? id);
    const prefix = style === 'revenue' ? 'generated by' : style === 'passiveParticiple' ? 'by' : 'for';
    clauses.push(`${prefix} ${joinNatural(names)}`);
  }

  if (supported.has('salesRep') && filters.repIds.length > 0) {
    const names = filters.repIds.map((id) => raw.sales_reps.find((r) => r.id === id)?.name ?? id);
    const prefix = style === 'generic' ? 'handled by' : 'through';
    clauses.push(`${prefix} ${joinNatural(names)}`);
  }

  if (supported.has('source') && filters.sources.length > 0) {
    const names = filters.sources.map((s) => SOURCE_LABELS[s] ?? s);
    clauses.push(`from ${joinNatural(names)}`);
  }

  if (supported.has('model') && filters.models.length > 0) {
    const prefix =
      style === 'revenue' ? 'from' : style === 'passiveParticiple' ? 'for' : question.calculation.type === 'count' ? 'interested in' : 'for';
    clauses.push(`${prefix} ${joinNatural(filters.models)}`);
  }

  if (supported.has('status') && filters.statuses.length > 0) {
    const labels = filters.statuses.map((s) => STATUS_LABELS[s] ?? s);
    clauses.push(`with status ${joinNatural(labels)}`);
  }

  if (supported.has('activeClosed') && filters.activeClosed !== 'all') {
    clauses.push(filters.activeClosed === 'active' ? 'that are currently active' : 'that are closed');
  }

  if (supported.has('deliveryStatus') && filters.deliveryStatus !== 'all') {
    clauses.push(filters.deliveryStatus === 'delivered' ? 'that have been delivered' : 'that have not been delivered');
  }

  if (supported.has('lostReason') && filters.lostReasons.length > 0) {
    clauses.push(`lost due to ${joinNatural(filters.lostReasons)}`);
  }

  if (supported.has('dealValueRange') && (filters.dealValueMin !== null || filters.dealValueMax !== null)) {
    if (filters.dealValueMin !== null && filters.dealValueMax !== null) {
      clauses.push(`with deal value between ${formatCurrency(filters.dealValueMin)} and ${formatCurrency(filters.dealValueMax)}`);
    } else if (filters.dealValueMin !== null) {
      clauses.push(`with deal value above ${formatCurrency(filters.dealValueMin)}`);
    } else if (filters.dealValueMax !== null) {
      clauses.push(`with deal value under ${formatCurrency(filters.dealValueMax)}`);
    }
  }

  if (supported.has('dateRange') && (filters.dateFrom || filters.dateTo)) {
    if (filters.dateFrom && filters.dateTo) {
      clauses.push(`between ${formatSentenceDate(filters.dateFrom)} and ${formatSentenceDate(filters.dateTo)}`);
    } else if (filters.dateFrom) {
      clauses.push(`from ${formatSentenceDate(filters.dateFrom)} onward`);
    } else if (filters.dateTo) {
      clauses.push(`up to ${formatSentenceDate(filters.dateTo)}`);
    }
  }

  if (supported.has('expectedCloseRange') && (filters.expectedCloseFrom || filters.expectedCloseTo)) {
    if (filters.expectedCloseFrom && filters.expectedCloseTo) {
      clauses.push(
        `expected to close between ${formatSentenceDate(filters.expectedCloseFrom)} and ${formatSentenceDate(filters.expectedCloseTo)}`,
      );
    } else if (filters.expectedCloseFrom) {
      clauses.push(`expected to close from ${formatSentenceDate(filters.expectedCloseFrom)} onward`);
    } else if (filters.expectedCloseTo) {
      clauses.push(`expected to close by ${formatSentenceDate(filters.expectedCloseTo)}`);
    }
  }

  if (clauses.length === 0) return question.question;

  const base = question.question.trim().replace(/\?+$/, '');
  return `${base} ${clauses.join(' ')}?`;
}
